### ISSUE TITLE
DEPRECATED - PHP 8.1.1

### ISSUE THREAD

**Issue by frase-git** [cmb69/advancedform_xh#89] opened 2022-06-26 09:00 UTC
> DEPRECATED: Return type of Advancedform\Form::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> ... \plugins\advancedform\classes\Form.php:182
> DEPRECATED: Return type of Advancedform\Field::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
> ... \plugins\advancedform\classes\Field.php:125

**Comment by cmb69** [comment] 2022-06-26 10:04
Isn't this a duplicate of #88, which already has been fixed in "master"?

**Comment by frase-git** [comment] 2022-06-26 10:11
Of course you are right, as always.
It's just stupid when you use the official version and not the master.
I had looked through the issues - but didn't find it. That I remember something like that - forget it ;-)

**Closed** 2022-06-26 10:11 UTC
