### ISSUE TITLE
Thanks pages not converted in 2.0?

### ISSUE THREAD

**Issue by manu37** [cmb69/advancedform_xh#65] opened 2021-02-21 17:03 UTC
It seems that the Thanks Page info is not covertet from forms.dat to forms.json.
When I try to add the Thanks Pages manually, hidded pages cannot get selected.
EDIT: Thanks pages are converted but are not shown/editable in forms edit.

**Comment by cmb69** [comment] 2021-02-21 17:13
This is likely a duplicate of #64. Can you please try with that patch (b52287eed51de6e02681d0d2f46dd7215766efd9)?

**Comment by manu37** [comment] 2021-02-21 17:20
> 
> 
> This is likely a duplicate of #64. Can you please try with that patch ([b52287e](https://github.com/cmb69/advancedform_xh/commit/b52287eed51de6e02681d0d2f46dd7215766efd9))?

works!

**Closed** 2021-02-21 17:31 UTC
Labels: duplicate
